---
- hosts: 172.31.10.150
  become: yes
  vars:
    myvar1: git
    myvar2: tree
    myvar3: wget
  tasks:  
- name: i want to dispay myvar1
  debug:
    msg: "{{myvar1}}"
- name: i want to intall  myvar1
  apt:
    name: "{{myvar1}}"
    state: present
    


