---
- hosts: 172.31.38.41
  become: yes
  vars:
     myvar1: git
     myvar2: tree
     myvar3: wget
  tasks:
  - name: i want to display myvar1
    debug:
      msg: "{{myvar1}}"  
  - name:
    apt:
      name: "{{myvar1}}"    
      sate: present
